path: ../
train: ../train/images
val: ../train/images
test: ../test/images

nc: 20
names: ['Open', 'Close', 'B5', 'B4', 'B3', 'B2', 'B1', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'Panel']

roboflow:
  workspace: elevator-rigpk
  project: sai-elevator
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/elevator-rigpk/sai-elevator/dataset/1